[channels.stable.plugins.MapLinker]
built_commit = "74deaa47e7948913595501e4ffcff39be7239959"
time_built = 2022-10-31T05:22:31.860
effective_version = "1.1.7.2"
[channels.stable.plugins.MapLinker.changelogs."1.1.7.2"]
time_released = 2022-10-31T05:22:31.860
changelog = "Fix linw wrap & UI mod during combat"
[channels.testing-live.plugins]
[channels.testing-net6.plugins]
