[channels.stable.plugins.MapLinker]
built_commit = "74deaa47e7948913595501e4ffcff39be7239959"
time_built = 2022-10-31T05:22:31.860
effective_version = "1.1.7.2"
[channels.stable.plugins.MapLinker.changelogs."1.1.7.2"]
time_released = 2022-10-31T05:22:31.860
changelog = "Fix linw wrap & UI mod during combat"
[channels.stable.plugins.ChatBubbles]
built_commit = "185e94da04f9a619b3b85e19f428303d7911f389"
time_built = 2022-11-12T23:54:47.706
effective_version = "2.1.2.0"
[channels.stable.plugins.ChatBubbles.changelogs."2.1.2.0"]
time_released = 2022-11-12T23:54:47.706
changelog = "Update for 6.2, API7 compatibility + UI update"
[channels.stable.plugins.UsedName]
built_commit = "4eb4883e357db09d9b96e49a50cc8c2fa6885cb6"
time_built = 2022-11-16T04:36:26.434
effective_version = "0.7.6.8"
[channels.stable.plugins.UsedName.changelogs."0.7.6.8"]
time_released = 2022-11-16T04:36:26.434
changelog = "- 修复.Net6兼容性问题\r\n"
[channels.testing-live.plugins.OBSPlugin]
built_commit = "88d676f25cb9712622656aba3f82e1929b1bb8b0"
time_built = 2022-11-13T00:02:00.424
effective_version = "1.0.2.1"
[channels.testing-live.plugins.OBSPlugin.changelogs]
[channels.testing-net6.plugins]
